apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    components: web
spec:
  containers:
    - name: client
      image: stephengrinder/multi-client
      ports:
        - containerPort: 3000 

